from typing import Any, Callable, Protocol

number = int | float

class IntPtrInitialized:
    pass


class FloatPtrInitialized:
    pass


class IntPtr:
    pass


class FloatPtr:
    pass


class VectorPtr:
    pass


class ReturnResultAnyway:
    pass


class ResultAsInteger:
    pass


class ResultAsFloat:
    pass


class ResultAsString:
    pass


class ResultAsVector:
    pass


class ResultAsLong:
    pass


class ResultAsObject:
    pass


class StateBagInterface:
    def __getitem__(self, key: str) -> Any: ...
    def set(self, key: str, value: Any, replicated: bool) -> None: ...


class EntityInterface:
    state: StateBagInterface


class CitizenInterface:
    def trace(self, *args: list[str]) -> None: ...
    def setTickFunction(self, callback: Callable) -> None: ...
    def setEventFunction(self, callback: Callable) -> None: ...
    def setCallRefFunction(self, callback: Callable) -> None: ...
    def setDeleteRefFunction(self, callback: Callable) -> None: ...
    def setDuplicateRefFunction(self, callback: Callable) -> None: ...
    def canonicalizeRef(self, ref: number) -> str: ...
    def invokeFunctionReference(self, ref: str, args: bytes) -> bytes: ...
    def getTickCount(self) -> number: ...
    def startProfiling(self, name: str | None = None) -> None: ...
    def stopProfiling(self, name: str | None = None) -> dict: ...
    def pointerValueIntInitialized(self) -> IntPtrInitialized: ...
    def pointerValueFloatInitialized(self) -> FloatPtrInitialized: ...
    def pointerValueInt(self) -> IntPtr: ...
    def pointerValueFloat(self) -> FloatPtr: ...
    def pointerValueVector(self) -> VectorPtr: ...
    def returnResultAnyway(self) -> ReturnResultAnyway: ...
    def resultAsInteger(self) -> ResultAsInteger: ...
    def resultAsFloat(self) -> ResultAsFloat: ...
    def resultAsString(self) -> ResultAsString: ...
    def resultAsVector(self) -> ResultAsVector: ...
    def resultAsLong(self) -> ResultAsLong: ...
    def resultAsObject(self) -> ResultAsObject: ...
    def makeRefFunction(self, refFunction: Callable) -> str: ...


class CitizenTimer:
    def ref(self) -> "CitizenTimer": ...
    def unref(self) -> "CitizenTimer": ...
    def hasRef(self) -> bool: ...
    def refresh(self) -> "CitizenTimer": ...


CitizenImmediate = CitizenTimer

Citizen: CitizenInterface = ...

def addRawEventListener(eventName: str, callback: Callable) -> None: ...

def setMaxRawEventListeners(max: number) -> None: ...

def addEventListener(eventName: str, callback: Callable, netSafe: bool | None = None) -> None: ...

def on(eventName: str, callback: Callable) -> None: ...

def AddEventHandler(eventName: str, callback: Callable) -> None: ...

def setMaxEventListeners(max: number) -> None: ...

def addNetEventListener(eventName: str, callback: Callable) -> None: ...

def onNet(eventName: str, callback: Callable) -> None: ...

def emit(eventName: str, *args: list[Any]) -> None: ...

def TriggerEvent(eventName: str, *args: list[Any]) -> None: ...

def emitNet(eventName: str, *args: list[Any]) -> None: ...

def TriggerServerEvent(eventName: str, *args: list[Any]) -> None: ...

def TriggerLatentServerEvent(eventName: str, bps: number, *args: list[Any]) -> None: ...

def getPlayerIdentifiers(player: number | str) -> list[str]: ...

def getPlayerTokens(player: number | str) -> list[str]: ...

def getPlayers() -> list[str]: ...

def SendNUIMessage(data: Any) -> None: ...

def emitNet(eventName: str, target: number | str, *args: list[Any]) -> None: ...

def TriggerClientEvent(eventName: str, target: number | str, *args: list[Any]) -> None: ...

def TriggerLatentClientEvent(eventName: str, target: number | str, bps: number, *args: list[Any]) -> None: ...

def removeEventListener(eventName: str, callback: Callable) -> None: ...

def setTimeout(callback: Callable[..., None], ms: number | None = None, *args: Any) -> CitizenTimer: ...

def clearTimeout(timeout: CitizenTimer) -> None: ...

def setInterval(callback: Callable[..., None], ms: number | None = None, *args: Any) -> CitizenTimer: ...

def clearInterval(interval: CitizenTimer) -> None: ...

def setImmediate(callback: Callable[..., None], *args: Any) -> CitizenImmediate: ...

def clearImmediate(immediate: CitizenImmediate) -> None: ...

def setTick(callback: Callable) -> number: ...

def clearTick(callback: number) -> None: ...

def NewStateBag(name: str) -> StateBagInterface: ...

def Entity(entity: number) -> EntityInterface: ...

def Player(entity: number | str) -> EntityInterface: ...

class CitizenExports:
    def __call__(self, exportKey: str | number, exportFunction: Callable) -> None: ...


exports: CitizenExports = ...

source: number = ...

class Console:
    def assert_(self, condition: bool | None = None, *data: list[Any]) -> None: ...
    def count(self, label: str | None = None) -> None: ...
    def countReset(self, label: str | None = None) -> None: ...
    def debug(self, *data: list[Any]) -> None: ...
    def dir(self, item: Any | None = None, options: Any | None = None) -> None: ...
    def error(self, *data: list[Any]) -> None: ...
    def info(self, *data: list[Any]) -> None: ...
    def log(self, *data: list[Any]) -> None: ...
    def time(self, label: str | None = None) -> None: ...
    def timeEnd(self, label: str | None = None) -> None: ...
    def trace(self, *data: list[Any]) -> None: ...
    def warn(self, *data: list[Any]) -> None: ...


console: Console = ...

